#!/bin/bash
# A backup list of my Emacs packages
# Author: Henry Newcomer

mkdir -p ~/.emacs.d/from_backup
cd ~/.emacs.d/from_backup

# Download files
git clone https://github.com/emacs-evil/evil.git
git clone https://github.com/sabof/org-bullets.git
git clone https://github.com/ejmr/php-mode.git
git clone http://www.dr-qubit.org/git/undo-tree.git

# eof
