#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Theme (via Prezto)
source ~/.zsh/themes/.purepower

# My custom aliases
alias cmaked='cmake -DCMAKE_BUILD_TYPE=DEBUG ..'
alias cmakem='cmake .. && make'

# Command completion
autoload -U compinit
compinit

# eof
